version: '2'
services:
    angularweb-app:
        image: angularweb
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://angularweb-mysql:3306/angularweb?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    angularweb-mysql:
        extends:
            file: mysql.yml
            service: angularweb-mysql
